# Generated by Django 5.2.5 on 2025-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
